### ISSUE TITLE
Push notification shows wrong deposit amount

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#763]
**Description**

Multiple push messages are sent on deposits. They then get merged to show a wrong amount. See attached video.

**Steps to Reproduce**

Deposit funds

**Expected behavior**

Push notifications shows correct amount

**Video**

https://github.com/stackernews/stacker.news/assets/27162016/d33f47c9-d307-40f5-b170-d7be5fe18721

**Additional context**

Probably related to #726

**Comment by ekzyis** [comment]
What I found out yesterday: It's related to reconnecting but I verified that the `finally` branch does execute. I thought it might not because we rethrow the error in `catch` but it does.

But seems like old subscriptions still continue to fire on reconnection.

**Comment by ekzyis** [comment]
Mhh, can't reproduce locally anymore

**Comment by huumn** [comment]
Wasn't this caused by what you fixed in #764?

**Comment by ekzyis** [comment]
> Wasn't this caused by what you fixed in #764?

No, #764 was only concerned with worker behavior on reconnects: it confirmed already paid invoices again.

This is about multiple push messages being sent per deposit. You can test in prod by deposit 100 sats. You should receive a deposit notification that says you deposited 400 sats.

Since only deposit notifications seem to be broken, I think this is related to the #726. But afaict, we correctly unsubscribe on errors. And as mentioned, wasn't able to reproduce locally.

Maybe we just need to restart the worker? When you deployed https://github.com/stackernews/stacker.news/commit/70aa7dd1ad6f3da7fee10044c284d8f27c7f3cfe, did you also restart the worker?

Or do you only restart it when there are changes to it? (I would guess the latter)

**Comment by huumn** [comment]
Everything rebuilds and restarts on every deployment.

**Comment by ekzyis** [comment]
> Everything rebuilds and restarts on every deployment.

Mhh, I still get "4 sats deposited" when someone sends me 1 sat.
